name: Android CI

on:
  push:
    branches:
      - development
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build BattFo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          gradle-version: '9.7.1'

      - name: Build APK
        run: gradle assembleDebug

      - name: Upload arm64-v8a APK
        uses: actions/upload-artifact@v4
        with:
          name: BattFo-arm64-v8a-debug
          path: app/build/outputs/apk/debug/*arm64-v8a*.apk

      - name: Upload armeabi-v7a APK
        uses: actions/upload-artifact@v4
        with:
          name: BattFo-armeabi-v7a-debug
          path: app/build/outputs/apk/debug/*armeabi-v7a*.apk

      - name: Upload x86_64 APK
        uses: actions/upload-artifact@v4
        with:
          name: BattFo-x86_64-debug
          path: app/build/outputs/apk/debug/*x86_64*.apk

      - name: Upload universal APK
        uses: actions/upload-artifact@v4
        with:
          name: BattFo-universal-debug
          path: app/build/outputs/apk/debug/*universal*.apk
